#+DATE: Time-stamp:
#+BEGIN_COMMENT
Spenserian stanza ababbcbcc
C-c C-, begin block structure
#+END_COMMENT
* Characters
** die Wirtin - the hostess
** der Wirt - the innkeeper
** der Graf - the Count
* 1
#+BEGIN_VERSE
When K. arrived, it was late in the night,
The village was covered under deep snow,
And the castle hill was nowhere in sight.
Fog and darkness enveloped him and though
The sky's faintest glow of light could not show
The outline of the great Palace, K. stood
On the wooden bridge, the darkness below,
The seeming emptiness was understood
To offer our hero the start of something good.
#+END_VERSE
* 2
<2024-02-07 Wed>
<2024-02-13 Tue>
#+begin_verse
And then, a decisive intake of air,
K. descended to the village below
Hoping to find lodgings anywhere there.
In the inn, peasants still stirred to and fro
In spite of the hour. There were no rooms, though
The Innkeeper offered a sack of straw,
And K.'s weariness had brought him so low
That he eagerly accepted as fair
The innkeeper's offer to sleep on the floor there.
#+end_verse
* 3
<2024-02-13 Tue>
#+begin_verse
But soon then K. was roused from his slumber
By a young man with a thespian's face.
The peasants were still there too in number
And many had turned from their beer in case
An entertaining spectacle took place.
The young man was dressed in fancy city
Clothes; his eyes were narrowed; it seemed the case
The young man was the son of a pretty
Big deal, and he was not trying to be witty!
#+end_verse
* 4
<2024-02-20 Tue>
#+begin_verse
A big deal indeed, the son of the Palace
Steward stood over K., his eyebrows strong,
Ready to torment with polite malice
Our poor K. over his excursion along
The village's outskirts lurking among
The shadows and darkness of the late hour.
You have entered the village was his song,
And the right to stay in any bower
Or hut, resided only in Count Westwest's power.
#+end_verse
* 5
<2024-02-20 Tue>
<2024-02-26 Mon>
#+begin_verse
Half sitting up and straightening his hair
K. nonchalantly glanced up at the crowd;
The innkeeper, the peasants in their chairs,
The young man asking if K. should be allow'd,
All waiting there for K. to speak out loud
His intentions on such a snowy night.
"Where am I?" K. asked as if he were proud
of his ignorance,  "I'm lost in the night."
He cried, "Palace you say? But there was not one in sight."
#+end_verse
* 6
<2024-02-26 Mon>
<2024-03-02 Sat>
#+begin_verse
The young man was astonished by K.'s act,
"Why indeed, the Palace of Count Westwest!"
"And you need the Count's permission, in fact,
For a weary travellor to simply rest
Overnight?" asked K. upon being press'd
By the expecting crowd. Was it a dream
That gave to him the notion that a guest
Could be so cruelly turned out? It did seem
To beggar belief. Such cruelty K. could not gleam.
#+end_verse
* 7
<2024-03-02 Sat>
<2024-03-09 Sat>
# Die Erlaubnis the permission ababbcbcc
# concern'd learn’d o’erturn’d earn'd inurn’d
# I eye why sky buy high ababbcbcc
# dwelling selling welling telling yelling
#+begin_verse
"You must have permission!" was the reply.
And with that, the dramatic young man turn'd
To his audience, and said with a sigh,
"Or maybe it's not required to have earn'd
The Count's blessings!" And now having so learn'd
The conditions of discretely dwelling
overnight, grasping that which so concern'd
the crowd, K. yawned, and perhaps overselling
his nonchalance, announced his plans without yelling.

#+end_verse
* 8
<2024-03-10 Sun>
<2024-03-17 Sun>
# seek shriek cheek week beak creek eke
# need steed meed proceed fee'd deed read
# scan outran began can fan ban than
#   ×  /  ×   /     ×   /     ×   /     ×   /
# When I do count the clock that tells the time
#+begin_verse
"Now, if it is permission that I need,"
Said K. "Then it is permission I seek."
And as if he were about to proceed,
Cast off his blanket with nary a peek
At the shocked crowd, barely able to speak.
"Permission from whom?" sputtered the young man,
"At this midnight hour?" he said with a shreik.
"It isn't possible?" and K. began
To yawn, "Why did you wake up a slumbering man?"
#+end_verse

* 9
<2024-03-20 Wed>
<2024-03-22 Fri>
<2024-03-24 Sun>
<2024-03-28 Thur>
<2024-03-29 Fri>
# rage page age sage wage stage cage dory glory sory
# sum from come dumb crumb plum glum drum scum hum
#+begin_verse
The young man was beside himself with rage,
"Why you're not but a low-down dirty bum!"
With a passion found only on the stage.
"The count demands respect! Not some sass from
A common tramp who's lower than pond scum!
You must depart the count's territory
At once!" At this, K. was able to drum
Up the peace of a saint in God's glory
"Enough!" he said and K. then began his story.
#+end_verse

* Interlude
#+begin_verse
Does K. feel despair? Does he cry in the night?
Is he so fixated on his mission
That he no longer dreads the morning light?
Why has he come here without permission?
Travelled so far on this expedition
Without a companion to help him through
The snow and darkness with precision.
Where is his family? Are they so few
That K. was attracted to the palace in view?
#+end_verse

* 11
<2024-04-02 Tue>
<2024-04-04 Thu>
# gentlemen when den then men again hen
# mount fount account amount surmount
# player mayor prayer layor
#+begin_verse
"I've had enough of your nonsense." said K,
"The Innkeeper and these good gentlemen
Are my witnesses should I need to sway
A jury of my peers. I take it then
You would like to know why I am here in
Your village. I am the land surveyor
Sent for by the Count. Now there, you see when
I saw the snow, layer upon layer,
I sat out on the trek after a hopeful prayer.
#+end_verse

* 12
<2024-04-07 Sun>
# state fate great date hate debate weight gate abate indicate plate
# roar door more sore before wore poor
#+begin_verse
"But, unfortunately, I lost my way
More than a few times and arrived so late
That I knew it was too late in the day
To report to the Palace in my state.
This is why I chose to accept my fate
And make do with camping out on the floor
Here in the corner. As much as I hate
To give up the comforts of a locked door
And a sweet bed, I knew my sleep would not be poor."
#+end_verse

* 13
<2024-04-07 Sun>
<2024-04-09 Tue>
<2024-04-10 Wed>
# drive contrive strive
# stow so below snow blow
# height light
#+begin_verse
"Tommorrow my assistants will arrive
Via carriage with the equipment in tow.
Now that's all that I'm willing to contrive
As far as an explanation will go.
Now goodnight fellas and, please, go pound snow!"
K. turned to the stove and pulled his blanket tight.
The Inn's mob retreated after K.'s show,
Confused by this information's new light,
They conversed in hushed tones while keeping K.in sight.
#+end_verse

* 14
<2024-04-11 Thu>
<2024-04-13 Sat>
# worth birth earth north
# dear steer cheer near here appear ear sneer
# job slob mob fob rob
#+begin_verse
"Surveyor?" the word was tossed back and forth,
And then a silence fell over the mob.
The young man, eager to show off his worth,
And now determined to finish the job,
Whispered in a tone so as not to rob
K. of his sleep but loud enough to hear
"I'll call the Palace, ask about this slob,
And check his story." he said with a sneer.
He headed to the phone and brought it close to his ear.
#+end_verse

* 15
<2024-04-13 Sat>
<2024-04-24 Wed>
# a case race deface face space
# b groan thrown own tone bone drone flown known alone
# brook'd ababbcbcc
# c sing ding ring swing king cling
#+begin_verse
"Good Goddamn!" thought K. to himself, "This place
Is decked out to the nines! They have a phone?"
Said telephone was crowded in a space
Directly above K.'s head. In his own
Weariness, among them all, he was alone
In overlooking the infernal thing.
Now K.'s restful sleep was sure to be blown
By the eager fellow's attempt to ring
The Palace. And now poor K. had to hear him sing.
#+end_verse

* 16
<2024-04-26 Fri>
<2024-04-28 Sun>
# merit, spirit, basket
# allow how bow wow scow now brow
#+begin_verse
Then the question was, would K. allow it?
He decided to allow it, but now
It was the case he could find no merit
In feigning sleep, he flipped o'er with a scow
And waited for the young man to find how
To inquire without disrupting K.'s sleep.
Across the way the dim light did allow
K. to see the bauern together deep
In discussion, in a corner, piled in a heap.
#+end_verse

* 17
<2024-04-28 Sun>
<2024-05-08 Wed>
<2024-05-11 Sat>
# blues choose say away delay clay way gay bay Landvermesser
# pay die Wirtin der Wirt warm norm uniform storm
#+begin_verse
K.'s arrival was no trivial news.
Surveyors don't pop up every day!
Every landlord had something to lose
If the Count changed the lines any old way.
The kitchen door was opened all the way,
And its frame filled by the landlady's form.
The host, eager to report on the fray,
Tiptoed in her direction to inform
The mighty Landlady of the incoming storm.
#+end_verse

*18
<2024-05-12 Sun>
<2024-05-18 Sat>
# can plan than man fan span deep creep cheap keep sweep weep leap
# clan plan can span wan deadpan ran began
#+begin_verse
The telephone conversation began.
The Palace Governor was sound asleep,
But one of his lackeys was the night man,
A certain Herr Fritz, who was known to keep
Some abysmally late hours sometimes deep
Into the night, was awake. The young man,
Going by Schwarzer, proceeded to leap
Into how he had found K., worn and wan,
Sleeping on a dirty straw sack, so he began.
#+end_verse

* 19
<2024-05-18 Sat>
<2024-05-28 Tue>
# hymn dim limb beauty grim moody booty
# task ask mask nation derivation location
# dury task burden, worth in, forth in, mask ask
# ABABBCBCC
#+begin_verse
Of course, Schwarzer was suspicious of him!
The landlord had neglected his duty;
And so the burden was his to, with grim
Determination, check out K.'s beauty
Of a tale. Awakening K.'s booty 
From a deep sleep, his interrogation
Of the man while he endured K.s snooty
Attitude, and threw his accusation
At K., along with expulsion from the nation.
#+end_verse

* 20
<2024-06-01 Sat>
<2024-06-15 Sat>
<2024-07-10 Wed>
# latitude attitude stood good solitude ingratitude
# sea he glee see she three bee free report short sort court
# pure secure obscure sure fewer
#+begin_verse
Schwarzer was shocked by K's ingratitude.
Perhaps rightly so, since K. claimed to be
A surveyor appointed to the good
By the Count his very own self and we
Can all assume that it's Scwarzer's duty
To verify K.'s claim, and so for sure
He was going to ask this Fritz to see
Into K.'s claim, that the Count did procure
His services, and of his motives, were they pure?
#+end_verse

* 21
<2024-07-15 Mon>
<2024-12-03 Tue>
# ask task mask return learn turn urn concern earn
# sigh I eye why try them gem condemn stem
# vase base
# ABABBCBCC
#+begin_verse
And then all was quiet. The whole lot of them
Waited with bated breath for Fritz to return
With the Palace's answer, a precious gem
Of information, so that they might learn
Could they send K. flying out with a stern
Flogging? And K.? He kept his poker face
Firmly intact and determined to earn
His spot with the rats in the Palace's race.
He stayed stoic, steadfast; his mask firmly in place.
#+end_verse

* 22
<2024-12-14 Sat>
<2024-12-15 Sun>
# riot diet
# care there air dare
#+begin_verse
Soon the phone's bray cut through the quiet.
It was Fritz, his report musta been brief
For Schwarzer, as if to start a riot,
Shouted, "I told you so!" in stark relief
And slammed down the receiver, "A liar-in-chief!
Nobody has heard of this surveyor!"
K. dove under his blanket in the belief
That Schwarzer, bauren, and everyone there
Would pounce upon poor K. right there without a care.
#+end_verse

* 23
<2024-12-15 Sun>
#+begin_verse
He waited for the assault with unease,
Under the blanket K. said a small prayer,
When the phone rang again it seemed to squeeze
the soul out of poor K. as he lay there.
He slowly poked his head out, with great care
And then watched Schwarzer return to the phone,
Meekly allowing the caller to share
A long story that led Schwarzer to groan,
"Mistake? How can I explain this all on my own?"
#+end_verse

* 24
<2024-12-17 Tue>
#+BEGIN_COMMENT
»Ein Irrtum also? Das
ist mir recht unangenehm. Der Bürochef selbst hat telefoniert? Sonderbar,
sonderbar. Wie soll ich es dem Herrn Landvermesser erklären?«

"A mistake, then? That
is quite unpleasant for me. The office manager himself made a phone call? Strange
strange. How am I to explain it to the surveyor?"

below so go slow show blow
fall all intellectual crawl
small tall wall mathematical additional
plight bright night
#+END_COMMENT

#+begin_verse
"This puts me in quite a pickle, you know,
And the office manager made the call?"
K. listened to this telephonic show
With great interest. Had the Palace all
but yielded to K. without even a brawl?
K. felt hope, saw light where there was no light
Before. Was the Palace totally in thrall
To its own power that it had lost sight
Of the freedom that K. would enjoy in the fight?
#+end_verse

* 25
# pen men then shock rock lock flock clock
# hawk talk block smile trial while style
#+begin_verse
But then, K. began to reflect again,
Perhaps the keen Palace had taken stock
Of him and, finding him wanting, had then
Likened him to Sisyphus and his rock,
A sad figure racing against the clock,
Suddenly the Palace had, with a smile,
Taken up the struggle to perhaps block
K.; His effort to join the village while
Enjoying a Palace job and living in style.
#+end_verse

* 26
<2024-12-20 Fri>
<2024-12-25 Wed>
#+begin_comment
boos blues booze fuse news whose lose hues
#+end_comment
#+begin_verse
Someone told falsehoods about Joseph K.
And as he lay in a peaceful slumber,
Strange men arrested him that faithful day.
It was not his choice to pluck a number
From a ticket dispenser and lumber
To the back of the line. He did not choose
To embrace the law that would encumber
His efforts, leading Joseph K. to lose
His own life to two men in fading twilight hues.
#+end_verse

* 27
<2024-12-26 Thu>
# way say gay spray clay mate late state estate plate gate
#+begin_verse
But, what can be said then of our poor K.?
He certainly chose his peculiar fate,
Groveling for a position all day,
Every day, no matter how small or great.
Sleeping away by the palace's gate
And prostrating himself before the law
Seasons will pass and K. will track the date
Until he is robbed of all that he saw
And is found dead in the winter's
And his poor body is found in the springtime's thaw
#+end_verse

* 28
<2025-01-30 Thu>
#+begin_verse
Schwarzer approached K. bowing and scraping,
But K. only shooed him off on his way.
K. was offered a chance of escaping
The pub for the innkeeper's room til day,
But K. shook his head and would only say
To bring a washbasin with soap and towel
Items the landlady brought right away.
The lamp was darkened, with a nary a growl
From the bauren as they left K. with the night owl.
#+end_verse

* 29
<2025-02-02 Sun>
<2025-02-03 Mon>
# more score door roar gore old behold cold
# Nach dem Frühstück (After breakfast)
#+begin_verse
K. slept so well that night there on the floor,a
Apart from a scurrying rat or two.b
Franz tells us not if he let out a snore,a
but only that he slept there so, so, true.b
Oh, and you should know that he was feed too.b
I'm sure the breakfast, though we are not told,c
Was solid and true. Payment was not due,b
said the innkeeper, all food, hot or cold,c
Was to be paid for by the palace's good gold. c
#+end_verse

* 30
<2025-02-03 Mon>
<2025-02-10 Mon>
<2025-02-13 Thu>
# bitty city ditty witty nitty pretty
#+begin_verse
K. polished off his meal and wanted to go
Straight to the village, but he took pity 
Upon the poor innkeeper, and then so 
Let the sad fellow sit down and pretty 
Much take a break. "I'm new to this city,
And my knowledge of the Count is so poor!"
Said K., "Is it true that he pays pretty
Well for good work? I would be mighty sore
If this weren't true, leaving my family and more."
#+end_verse

* 31
<2025-02-15 Sat>
# story hoary promontory glory hurry gory dory
# I perch upon an humbler promontory, hovel grovel
# brown clown crown noun frown renown own
#+begin_verse
Wow, K. with wife and child? This backstory
will come to nought, dear reader, so calm down!
We perch on a distant promontory,
And can no longer see what was once known.
Is K. lying? Did Kafka mess around
And not finish his wonderful novel?
Leaving another king without a crown,
An idea left rotting in a hovel,
Never to know, no matter how much we grovel.
#+end_verse

* 32
<2025-02-17 Mon>
<2025-02-18 Tue>
<2025-03-01 Sat>
# accord word tell miracle cell shell dwell
#+begin_verse
"I don't hear any gripes about the Lord,"a
Said the innkeeper, "He pays fairly well."b
"I'm not afraid to put in a good word a
For myself!" said K. "I would like to sell b
My skills personally to the Herren." c
The Wirt seemed to retreat into his shell b
As he perched anxiously on his barren c
Windowsill. What fear and terrors did dwell
In the poor man's chest? Did he see Charon
Waiting to ferry his soul across the Acheron?
#+end_verse

* 33
<2025-03-08 Sat>
<2025-03-15 Sat>
# prize surprise wise disguise dies
# chose rose knows those rose arose repose undergoes
#+begin_verse
The Wirt there with his big brown anxious eyes,
K. just had to distract him from his woes.
"My assistants," said K. "I would surmise,
Will soon be here. So, if the need arose, 
Can you provide rooms for them to repose?"
"Certainly," he said, "but will they not stay
With you at the Palace?" K. shrugged. "Who knows
What work they have for me from day to day.
You see, I may need to stay down here, who can say?"
#+end_verse

* 34
<2025-03-19 Wed>
# sigh eye sky high die why prone shown bone own grown known alone throne
# down gown clay pray way
#+begin_verse
"You don't know the Palace." was the reply a
The Wirt gave him in an awed and hushed tone. b
K. considered this and then with a sigh a 
Said, "My ego is big, but I can be shown b
the error and shortcomings of my own b
Beliefs. About the Palace, all I can say, c
Is that they know how to find (all alone!) b
The right land surveyor, but staying way
Up there could have its advantages you might say."

the error of my assumptions 8
That I can't be shown
Said, "I can see your point  be shown b
The error of my assumptions" b
#+end_verse

* 35
<2025-03-22 Sat>
<2025-03-26 Wed>
# year tear here cheer guest rest nest chest detest
#+begin_verse
The Wirt began to bite his lip in fear,
And a pang of pity rose in K.'s breast.
What would it take to give this man good cheer?
K. rose from his seat; he had done his best 
To set the Wirt at ease, but now the rest 
Of his day needed to begin. As he 
Was leaving, a portrait of a depressed
Figure of a man on the wall caught the
Corner of K.'s eye; he approached it so to see.
#+end_verse

* 36
<2025-03-26 Wed>
# din wherein twin been wit fit permit dread dead wed bred
# span fan van than plan wise size
#+begin_verse
The half-length portrait was of a spirit,
'Bout fifty years of age, with a forehead
So ponderous and so heavy that it
Seemed to depress his chin, it could be said,
Into his chest. His head was sunk so it  
Was nigh impossible to see his eyes. 
His hand clutched his thick hair as if unfit
To support a head that could not arise -
Like Lazarus from the grave, to its former size.
#+end_verse
#+begin_verse
The half-length portrait there was of a man
With a forehead so ponderous that it
Caused his chin to sink and his beard to fan
Out spreading across his chest 7 
Seemed to press his chin 5 
#+end_verse
#+begin_quote
As K. was going out he noticed a dark portrait in a dim frame on the wall. He had already (schon)
observed it from his couch (Lager) by the stove, but from that distance he had not been able to
distinguish any details and had thought that it was only a plain back to the frame. But it was a
picture after all, as now appeared, the bust portrait of a man about fifty. His head was sunk so low
upon his breast that his eyes were scarcely visible, and the weight of the high, heavy forehead and
the strong hooked nose seemed to have borne the head down. Because of this pose the man's full beard
was pressed in at the chin and spread out farther down. His left hand was spread out in his thick
hair but could no longer support his head.
#+end_quote
* 37
#+begin_verse
To exact of Cupid’s bills the full amount
At sight, nor would permit you to discount.
#+end_verse
#+begin_verse
K. stood in front of the gloomy picture.a
"Who is that?" asked K. "Is that the Count?"b
K. spoke aloud without guile or stricture,a
Not looking or taking into accountb
The presence of the Wirt and the amountb
That could then be heard. The Wirt shook his headc
"No," he said in a whisper, "Not the Count,b
But the Palace Governor." The Wirt's dread
Was palpable in a way that could not be read.
#+end_verse
* 38
<2025-04-22 Tue>
<2025-04-29 Tue>
<2025-04-30 Wed>
#+begin_verse
"Such a handsome gov'nor in the Palace."
Said K. "Pity 'bout his brat of a son!"
The Wirt pulled K. closer without malice
And whispered, "Schwarzer's full of a fuckton
of shit! His father's a subgov'nor, one
Of the lowest at that!" "The devil!"(Der Lump)
laughed K, but the Wirt didn't join in the fun.
"Oh, His father is totally high-level!"
In the paranoia, K began to revel. 
#+end_verse
* 39
<2025-04-30 Wed>
<2025-05-01 Thu>
# view do 
#+begin_verse
"Here and there you see powerful people!
How about me? Am I powerful too?"
The Wirt said, "No you're one of the sheeple."
"I can tell that you've got me pegged, that's true.
But, you see, I'm not as honest as you,
I respect them, I don't care to admit it."
K. tapped him on his cheek in order to
Gain his affection and he saw it
Bring the faintest smile to his face for a visit.
#+end_verse
* 40
<2025-05-01 Thu>
<2025-05-02 Fri>
# joy destroy employ enjoy
#+begin_verse
The smile transformed the Wirt into a boy,
What with his soft and almost beardless face.
How did he find himself in spousal joy
With an older corn-fed gal in this place?
K. spied the Wirtin through an open space
In the kitchen with her elbows sticking
Out and decided that he need not chase
The matter any further. Heels clicking,
K. set out to give the beautiful day a licking.
#+end_verse
* 41
<2025-05-09 Fri>
<2025-05-11 Sun>
# show foe know snow
#+begin_verse
The Palace was framed against the clear air,
And it loomed above the village below.
It met K's expectations hanging there.
It was not some musty old castle, oh
No! Nor an ornate building just for show,
But rather a jumble of squat buildings,
With only one tower K. could not know
If it was a church without the gilding
But alas, naming such things he was not skilled in.
#+end_verse
* 42
<2025-05-11 Sun>
<2025-05-24 Sat>
# grocer dozer poser bulldozer said dead wed read bred spread bled
# crown renown down
#+begin_verse
K. soldiered on with his eyes fixed ahead
On the Palace. But as our K. came near
The sight of the Palace began to spread
Out before him; he was struck by a fear.
It was not a showy sight, that was clear,
Rather a miserable little town
Assembled from stone houses in such a queer
Manner. A wave of displeasure crashed down
Upon him. How could this place command such renown?
#+end_verse
* 43
<2025-05-27 Tue>
<2025-05-29 Thu>
# glory hurry pardon bard in warden banner manor harden
#+begin_verse
K. stopped in front of a long one-storey
Building hiding behind a fenced garden
That was now covered in snowy glory.
Just then a gang of kids and their warden
Poured out of the building, beg your pardon,
Left the school in an orderly manner.
The children drew up short like a bard in
Thought and crowded 'neath their teacher's banner,
Staring at K. and loudly raising a clamor.
#+end_verse
* 44
<2025-06-02 Mon>
# be see free sea grim me
#+begin_verse
The teacher was a young small man with slim a
Shoulders and an upright posture, but he b
Was not ridiculous, oh no, but trim. a
K. stood all alone, only he could be b
Seen. So, not to appear as out to sea, b
K. chose to speak first, "Good day, Herr Teacher." c
An eerie silence settled upon the b
Group, like the calm called for by a preacher.
The young man gestured towards a village feature.
#+end_verse
* 45
<2025-06-03 Tue>
<2025-06-04 Wed>
<2025-06-06 Fri>
<2025-06-09 Mon>
# maid aid head dead led staid bed dread read
# right might light sight tight masked site vast right past bright
#+begin_verse
"Are you looking at the Palace?" he said.
"Yes," said K. "I only arrived last night.
Went for a stroll and decided to head
Out this cold morning to check out the sight
of the Palace." Something was not all right,
"You don't like the Palace?" the teacher asked
Abruptly. At that K. found himself quite
Taken aback. "What?" K. said to the last
Question. But then K. gave his response a new cast.
#+end_verse
* 46
<2025-06-10 Tue>
# touch crutch dutch
#+begin_verse
"Why do you think I don't like the Palace?"
K. asked. "No stranger likes it very much."
Was the reply. K. was full, like Alice
In Through the Looking Glass, of questions such
As, "You must know the Count?" with just a touch
Of eagerness. "No!" the teacher replied
And turned to leave, but K. knocked his crutch
Away with "How? The Count is far and wide
Known everywhere, how can you stand to act so snide?"
#+end_verse
* 47
<2025-06-12 Thu>
# can fan tan than
#+begin_verse
"How should I know the Count?" cried the teacher.
He gestured and said, "Enfants innocents!"
But discouragement was not a feature
of K.'s core nature. K. asked, "Can I plan
On paying you a visit my good man?"
And quickly wrapped himself in self-pity.
"I belong among the elite rather than
The plebian bauren and their gritty
Ways. Nor the Palace and it's surrounding city."
#+end_verse
* 48
<2025-06-13 Fri>
<2025-06-15 Sun>
# blame lame flame game sea 
#+begin_verse
"The bauren and the Palace are the same."
The teacher said with a shrug. "That may be,"
K. replied, "But it doesn't change the game.
Can I pay you a visit?" He said that he
Lived on Swan Street, but it was without glee,
More like a statement of fact than an invite.
K. pressed ahead, "Good, I will come and see
You." The teacher nodded in morning's light,
And he and the kiddie gang were soon out of sight.
#+end_verse
* 49
<2025-06-16 Mon>
#+begin_verse
Suddenly the very wind left K.'s sails.
He felt tired, real fatigue for the first time
Since he arrived, treking through snow and gales,
Calmly taking step by step the long climb
To the village inn, needing neither rails
Nor horse to accomplish his long journey.
He needed someone to listen to his tales,
But much like a sick man on a gurney,
Each acquaintance was like a boring attorney.
#+end_verse
* 50
<2025-06-17 Tue>
#+begin_verse
K. so needed to reach the Palace gate,
He started, but it was such a long way.
How far could he go in his current state?
The main road did not lead in any way
to the Palace Hill, in the light of day
It only seemed, to K.'s eyes, to come close
Only to perversely turn just away,
As if the road had an instinct to cross
K.'s very intentions and guffaw at his loss.
#+end_verse
* 51
<2025-06-20 Fri>
<2025-07-02 Wed>
<2025-07-03 Thu>
# displayed palisade said conveyed know so slow
#+begin_verse
The village was an unending parade
Of tiny houses behind mounds of snow
And frosted windows, while the streets displayed
Their emptiness in an unearthly show.
K. continued plodding on the road, though
It did not turn back towards or away
From the Palace. K. stopped. He could not know
If the village road lead in any way
To the Palace and turned away from the roadway.
#+end_verse
* 52
<2025-07-20 Sun>
<2025-07-22 Tue>
#+begin_verse
Down a narrow alley he turned, his feet
Sinking deeper into the piles of snow.
Sweat broke out and he could feel his heart beat
Against his chest. Then K. stopped and could go
No further. His exhaustion had brought him low.
Why had he left the safety of the main
Road? Now to go out like some common joe?
But he was not lost on some desert plain,
For Bauren cottages lined both sides of the lane.
#+end_verse
* 53
<2025-07-23 Wed>
# fenced sensed tensed incensed incensed ride lied
# pride wide dried tried groove prove remove
#+begin_verse
K. knelt down low and fashioned a snowball
He took careful aim and threw it up side
A window. A door opened and a small
Old bauren in a coat stood there.  K. cried
Out. "May I come in for a spell? I tried
To reach the Palace, but I can not move
Another foot!" A board began to slide
Towards him and a few steps would remove
Him from the snow and his plight would greatly improve.

Old bauren in a coat stood there.  K. sensed
The man's good nature and began to call
Out, "May I come in? I can barely crawl
Another foot. Exhaustion has gripped me!"
#+end_verse
* 54
<2025-07-24 Thu>
<2025-07-28 Mon>
# core before more shore
`#+begin_verse
At first, K. couldn't see shit. The large room
Was dimly lit and K. soon stumbled o'er
A washtub. A hand reached out from the gloom,
(A woman's hand) to steady him, before
K. could take a tumble down to the floor.
From one corner came the screams of children
And from another smoke billowed forth more
And more, casting in a bewildering
Way the light into a darkness quivering.
#+end_verse
* 55
<2025-07-28 Mon>
# read dead bed
#+begin_verse
K. stood there dumbly as if in a cloud.
"Who let the boozer in?" someone called out,
"Who is he? Are you going to allow
Anyone to wander in off the route?"
"I am the land surveyor." K., without
Being able to see anyone, said.
"Oh hell, the surveyor." A voice about
A few feet away said. K. turned his head,
But still, he could not make out the living or dead.
#+end_verse
* 56
<2025-07-28 Mon>
<2025-07-30 Wed>
# bout clout trout pout scout raising
#+begin_verse
Finally, the room's smoke began to clear,
And K. was able to make some things out.
He saw that laundry was being washed near
The door and a big wooden tub, about
The size of two beds, was without a doubt
The source of the smoke. Two men were bathing
Together like a couple of fat trout
In the steaming water. Pale snow-kissed rays
Streamed in from a gap in the back, cutting the haze.

One was raising
His voice, "Sit Down!", 4 said the 6 fellow 8 in need of 
shaving
His voice, the one in serious need of a shaving.
#+end_verse
* 57
<2025-08-01 Fri>
<2025-08-02 Sat>
# vigour rigour disfigure trigger bigger nest
#+begin_verse
The light fell gently upon the figure
Of a madonna with child at her breast.
The pale light bathed her dress with a vigor
That gave the garment a silken sheen blessed
By the northen sunlight. What had so stressed
K. for the past few days melted away.
Bauren children played near her, but at best,
She was just merely of them, you could say,
But she did not seem to belong to them that day. 
#+end_verse
* 58
# club scrub lover get over cover "prove her" discover
#+begin_verse
"Sit down!" came a shout from the wooden tub.
A bushy-bearded 5 soul gestured over
The edge of the tub, splashing water up
In K.'s face, leading him to discover
The old man dozing without any cover
On a chest in the corner of the room.
K. desired a seat more than a lover
Could desire their beau clothed in rich perfume.
His weariness wrapped him in an oppressive gloom.

One of the bathers directed K.'s gaze
To a chest 
K.'s gaze was directed to a chest
A bather with a full beard pointed 

A man with a bushy beard  
#+end_verse
* 59
<2025-08-12 Tue>
<2025-08-27 Wed>
#+begin_verse
Grateful for a chance to finally sit,
K. plopped down next to the napping old man.
Now no one cared about him. The young fit
Blonde woman at the washing trough began    # sang leise bei der Arbeit,
To sing softly as she worked, the kids ran
Around the wooden tub as the men sent
Potent splashes of water at the clan
of urchins. The bath water did not dent
K. one bit, 3 he 4 only 6 thought of 8 sleep9 heaven12 sent.
#+end_verse
* 60
<2025-08-29 Fri>
<2025-08-30 Sat>
# 2 Corinthians 11:25 
#+begin_verse
Every epic demands a trip to sea. a
Paul was shipwrecked thrice and beaten with rods. b
A freakin' snake bit him and, like a boss, he a
Just tossed it off, I mean, what are the odds b
He was just trying to impress the broads? b
Don Juan set sail for Cádiz before
Finding his ship upended by the gods
And cast adrift in the Aegean
c
Aegean Sea
That he was serving a load of hooey?
Don Juan set sail to Cádiz
#+end_verse
* 61
<2025-09-01 Mon>
#+begin_verse
Oh, but K. is not destined for the sea!
You see, he will not hear the sirens' call
Or blind Polyphemus with a charred tree.
Instead he stares at the woman in thrall
To the armchair, appearing to be all
But lifeless, not even seeing the child
At her breast, vaguely staring at the wall
Beyond. To K.'s eyes the sight appeared mild
And ever unchanging, sad and carefully styled.

He must have slipp'd 'to a mild
Sleep, his head was on the old man when K. was riled.
#+end_verse
* 62
<2025-09-01 Mon>
#+begin_verse
A loud voice jolted K. awake
#+end_verse
