#+BEGIN_COMMENT
Spenserian stanza ababbcbcc
C-c C-, begin block structure
#+END_COMMENT
* Characters
** die Wirtin - the hostess
** der Wirt - the innkeeper
* 1
#+BEGIN_VERSE
When K. arrived, it was late in the night,
The village was covered under deep snow,
And the castle hill was nowhere in sight.
Fog and darkness enveloped him and though
The sky's faintest glow of light could not show
The outline of the great Palace, K. stood
On the wooden bridge, the darkness below,
The seeming emptiness was understood
To offer our hero the start of something good.
#+END_VERSE
* 2
<2024-02-07 Wed>
<2024-02-13 Tue>
#+begin_verse
And then, a decisive intake of air,
K. descended to the village below
Hoping to find lodgings anywhere there.
In the inn, peasants still stirred to and fro
In spite of the hour. There were no rooms, though
The Innkeeper offered a sack of straw,
And K.'s weariness had brought him so low
That he eagerly accepted as fair
The innkeeper's offer to sleep on the floor there.
#+end_verse
* 3
<2024-02-13 Tue>
#+begin_verse
But soon then K. was roused from his slumber
By a young man with a thespian's face.
The peasants were still there too in number
And many had turned from their beer in case
An entertaining spectacle took place.
The young man was dressed in fancy city
Clothes; his eyes were narrowed; it seemed the case
The young man was the son of a pretty
Big deal, and he was not trying to be witty!
#+end_verse
* 4
<2024-02-20 Tue>
#+begin_verse
A big deal indeed, the son of the Palace
Steward stood over K., his eyebrows strong,
Ready to torment with polite malice
Our poor K. over his excursion along
The village's outskirts lurking among
The shadows and darkness of the late hour.
You have entered the village was his song,
And the right to stay in any bower
Or hut, resided only in Count Westwest's power.
#+end_verse
* 5
<2024-02-20 Tue>
<2024-02-26 Mon>
#+begin_verse
Half sitting up and straightening his hair
K. nonchalantly glanced up at the crowd;
The innkeeper, the peasants in their chairs,
The young man asking if K. should be allow'd,
All waiting there for K. to speak out loud
His intentions on such a snowy night.
"Where am I?" K. asked as if he were proud
of his ignorance,  "I'm lost in the night."
He cried, "Palace you say? But there was not one in sight."
#+end_verse
* 6
<2024-02-26 Mon>
<2024-03-02 Sat>
#+begin_verse
The young man was astonished by K.'s act,
"Why indeed, the Palace of Count Westwest!"
"And you need the Count's permission, in fact,
For a weary travellor to simply rest
Overnight?" asked K. upon being press'd
By the expecting crowd. Was it a dream
That gave to him the notion that a guest
Could be so cruelly turned out? It did seem
To beggar belief. Such cruelty K. could not gleam.
#+end_verse
* 7
<2024-03-02 Sat>
<2024-03-09 Sat>
# Die Erlaubnis the permission ababbcbcc
# concern'd learn’d o’erturn’d earn'd inurn’d
# I eye why sky buy high ababbcbcc
# dwelling selling welling telling yelling
#+begin_verse
"You must have permission!" was the reply.
And with that, the dramatic young man turn'd
To his audience, and said with a sigh,
"Or maybe it's not required to have earn'd
The Count's blessings!" And now having so learn'd
The conditions of discretely dwelling
overnight, grasping that which so concern'd
the crowd, K. yawned, and perhaps overselling
his nonchalance, announced his plans without yelling.

#+end_verse
* 8
<2024-03-10 Sun>
<2024-03-17 Sun>
# seek shriek cheek week beak creek eke
# need steed meed proceed fee'd deed read
# scan outran began can fan ban than
#   ×  /  ×   /     ×   /     ×   /     ×   /
# When I do count the clock that tells the time
#+begin_verse
"Now, if it is permission that I need,"
Said K. "Then it is permission I seek."
And as if he were about to proceed,
Cast off his blanket with nary a peek
At the shocked crowd, barely able to speak.
"Permission from whom?" sputtered the young man,
"At this midnight hour?" he said with a shreik.
"It isn't possible?" and K. began
To yawn, "Why did you wake up a slumbering man?"
#+end_verse

* 9
<2024-03-20 Wed>
<2024-03-22 Fri>
<2024-03-24 Sun>
<2024-03-28 Thur>
<2024-03-29 Fri>
# rage page age sage wage stage cage dory glory sory
# sum from come dumb crumb plum glum drum scum hum
#+begin_verse
The young man was beside himself with rage,
"Why you're not but a low-down dirty bum!"
With a passion found only on the stage.
"The count demands respect! Not some sass from
A common tramp who's lower than pond scum!
You must depart the count's territory
At once!" At this, K. was able to drum
Up the peace of a saint in God's glory
"Enough!" he said and K. then began his story.
#+end_verse

* Interlude
#+begin_verse
Does K. feel despair? Does he cry in the night?
Is he so fixated on his mission
That he no longer dreads the morning light?
Why has he come here without permission?
Travelled so far on this expedition
Without a companion to help him through
The snow and darkness with precision.
Where is his family? Are they so few
That K. was attracted to the palace in view?
#+end_verse

* 11
<2024-04-02 Tue>
<2024-04-04 Thu>
# gentlemen when den then men again hen
# mount fount account amount surmount
# player mayor prayer layor
#+begin_verse
"I've had enough of your nonsense." said K,
"The Innkeeper and these good gentlemen
Are my witnesses should I need to sway
A jury of my peers. I take it then
You would like to know why I am here in
Your village. I am the land surveyor
Sent for by the Count. Now there, you see when
I saw the snow, layer upon layer,
I sat out on the trek after a hopeful prayer.
#+end_verse

* 12
<2024-04-07 Sun>
# state fate great date hate debate weight gate abate indicate plate
# roar door more sore before wore poor
#+begin_verse
"But, unfortunately, I lost my way
More than a few times and arrived so late
That I knew it was too late in the day
To report to the Palace in my state.
This is why I chose to accept my fate
And make do with camping out on the floor
Here in the corner. As much as I hate
To give up the comforts of a locked door
And a sweet bed, I knew my sleep would not be poor."
#+end_verse

* 13
<2024-04-07 Sun>
<2024-04-09 Tue>
<2024-04-10 Wed>
# drive contrive strive
# stow so below snow blow
# height light
#+begin_verse
"Tommorrow my assistants will arrive
Via carriage with the equipment in tow.
Now that's all that I'm willing to contrive
As far as an explanation will go.
Now goodnight fellas and, please, go pound snow!"
K. turned to the stove and pulled his blanket tight.
The Inn's mob retreated after K.'s show,
Confused by this information's new light,
They conversed in hushed tones while keeping K.in sight.
#+end_verse

* 14
<2024-04-11 Thu>
<2024-04-13 Sat>
# worth birth earth north
# dear steer cheer near here appear ear sneer
# job slob mob fob rob
#+begin_verse
"Surveyor?" the word was tossed back and forth,
And then a silence fell over the mob.
The young man, eager to show off his worth,
And now determined to finish the job,
Whispered in a tone so as not to rob
K. of his sleep but loud enough to hear
"I'll call the Palace, ask about this slob,
And check his story." he said with a sneer.
He headed to the phone and brought it close to his ear.
#+end_verse

* 15
<2024-04-13 Sat>
<2024-04-24 Wed>
# a case race deface face space
# b groan thrown own tone bone drone flown known alone
# brook'd ababbcbcc
# c sing ding ring swing king cling
#+begin_verse
"Good Goddamn!" thought K. to himself, "This place
Is decked out to the nines! They have a phone?"
Said telephone was crowded in a space
Directly above K.'s head. In his own
Weariness, among them all, he was alone
In overlooking the infernal thing.
Now K.'s restful sleep was sure to be blown
By the eager fellow's attempt to ring
The Palace. And now poor K. had to hear him sing.
#+end_verse

* 16
<2024-04-26 Fri>
<2024-04-28 Sun>
# merit, spirit, basket
# allow how bow wow scow now brow
#+begin_verse
Then the question was, would K. allow it?
He decided to allow it, but now
It was the case he could find no merit
In feigning sleep, he flipped o'er with a scow
And waited for the young man to find how
To inquire without disrupting K.'s sleep.
Across the way the dim light did allow
K. to see the bauern together deep
In discussion, in a corner, piled in a heap.
#+end_verse

* 17
<2024-04-28 Sun>
<2024-05-08 Wed>
<2024-05-11 Sat>
# blues choose say away delay clay way gay bay Landvermesser
# pay die Wirtin der Wirt warm norm uniform storm
#+begin_verse
K.'s arrival was no trivial news.
Surveyors don't pop up every day!
Every landlord had something to lose
If the Count changed the lines any old way.
The kitchen door was opened all the way,
And it's frame filled by the landlady's form.
The host, eager to report on the fray,
Tiptoed in her direction to inform
The mighty Landlady of the incoming storm.
#+end_verse

*18
<2024-05-12 Sun>
<2024-05-18 Sat>
# can plan than man fan span deep creep cheap keep sweep weep leap
# clan plan can span wan deadpan ran began
#+begin_verse
The telephone conversation began.
The Palace Governor was sound asleep,
But one of his lackeys was the night man,
A certain Herr Fritz, who was known to keep
Some abysmally late hours sometimes deep
Into the night, was awake. The young man,
Going by Schwarzer, proceeded to leap
Into how he had found K., worn and wan,
Sleeping on a dirty straw sack, so he began.
#+end_verse

* 19
<2024-05-18 Sat>
<2024-05-28 Tue>
# hymn dim limb beauty grim moody booty
# task ask mask nation derivation location
# dury task burden, worth in, forth in, mask ask
# ABABBCBCC
#+begin_verse
Of course, Schwarzer was suspicious of him!
The landlord had neglected his duty;
And so the burden was his to, with grim
Determinati1on, check out K.'s beauty
Of a tale. Awakening K.'s booty 
From a deep sleep, his interrogation
Of the man while he endured K.s snooty
Attitude, and threw his accusation
At K., along with expulsion from the nation.
#+end_verse

* 20
<2024-06-01 Sat>
<2024-06-15 Sat>
<2024-07-10 Wed>
# latitude attitude stood good solitude ingratitude
# sea he glee see she three bee free report short sort court
# pure secure obscure sure fewer
#+begin_verse
Schwarzer was shocked by K's ingratitude.
Perhaps rightly so, since K. claimed to be
A surveyor appointed to the good
By the Count his very own self and we
Can all assume that it's Scwarzer's duty
To verify K.'s claim, and so for sure
He was going to ask this Fritz to see
Into K.'s claim, that the Count did procure
His services, and of his motives, were they pure?
#+end_verse

* 21
<2024-07-15 Mon>
<2024-12-03 Tue>
# ask task mask return learn turn urn concern earn
# sigh I eye why try them gem condemn stem
# vase base
# ABABBCBCC
#+begin_verse
And then all was quiet. The whole lot of them
Waited with bated breath for Fritz to return
With the Palace's answer, a precious gem
Of information, so that they might learn
Could they send K. flying out with a stern
Flogging? And K.? He kept his poker face
Firmly intact and determined to earn
His spot with the rats in the Palace's race.
He stayed stoic, steadfast; his mask firmly in place.
#+end_verse

* 22
<2024-12-14 Sat>
<2024-12-15 Sun>
# riot diet
# care there air dare
#+begin_verse
Soon the phone's bray cut through the quiet.
It was Fritz, his report musta been brief
For Schwarzer, as if to start a riot,
Shouted, "I told you so!" in stark relief
And slammed down the receiver, "A liar-in-chief!
Nobody has heard of this surveyor!"
K. dove under his blanket in the belief
That Schwarzer, bauren, and everyone there
Would pounce upon poor K. right there without a care.
#+end_verse

* 23
<2024-12-15 Sun>
#+begin_verse
He waited for the assault with unease,
Under the blanket K. said a small prayer,
When the phone rang again it seemed to squeeze
the soul out of poor K. as he lay there.
He slowly poked his head out, with great care
And then watched Schwarzer return to the phone,
Meekly allowing the caller to share
A long story that led Schwarzer to groan,
"Mistake? How can I explain this all on my own?"
#+end_verse

* 24
<2024-12-17 Tue>
#+BEGIN_COMMENT
»Ein Irrtum also? Das
ist mir recht unangenehm. Der Bürochef selbst hat telefoniert? Sonderbar,
sonderbar. Wie soll ich es dem Herrn Landvermesser erklären?«

"A mistake, then? That
is quite unpleasant for me. The office manager himself made a phone call? Strange
strange. How am I to explain it to the surveyor?"

below so go slow show blow
fall all intellectual crawl
small tall wall mathematical additional
plight bright night
#+END_COMMENT

#+begin_verse
"This puts me in quite a pickle, you know,
And the office manager made the call?"
K. listened to this telephonic show
With great interest. Had the Palace all
but yielded to K. without even a brawl?
K. felt hope, saw light where there was no light
Before. Was the Palace totally in thrall
To its own power that it had lost sight
Of the freedom that K. would enjoy in the fight?
#+end_verse

# pen men then shock rock lock flock clock
# hawk talk block smile trial while style
#+begin_verse
But then, K. began to reflect again,
Perhaps the keen Palace had taken stock
Of him and, finding him wanting, had then
Likened him to Sisyphus and his rock,
A sad figure racing against the clock,
Suddenly the Palace had, with a smile,
Taken up the struggle to perhaps block
K.; His effort to join the village while
Enjoying a Palace job and living in style.
#+end_verse
<2024-12-20 Fri>
<2024-12-25 Wed>
#+begin_comment
boos blues booze fuse news whose lose hues
#+end_comment
#+begin_verse
Someone told falsehoods about Joseph K.
And as he lay in a peaceful slumber,
Strange men arrested him that faithful day.
It was not his choice to pluck a number
From a ticket dispenser and lumber
To the back of the line. He did not choose
To embrace the law that would encumber
His efforts, leading Joseph K. to lose
His own life to two men in fading twilight hues.
#+end_verse
<2024-12-26 Thu>
# way say gay spray clay mate late state estate plate gate
#+begin_verse
But, what can be said then of our poor K.?
He certainly chose his peculiar fate,
Groveling for a position all day,
Every day, no matter how small or great.
Sleeping away by the palace's gate
And prostrating himself before the law
Seasons will pass and K. will track the date
Until he is robbed of all that he saw
And is found dead in the winter's
And his poor body is found in the springtime's thaw
#+end_verse
